[deps]
CompariMotif = "aecef331-8c7a-44c4-b913-ba8debb6e116"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.10"
DataFrames = "1"
Documenter = "1"
